version: '3.8'

services:
  app:
    container_name: espace-elite-app
    build: .
    restart: always
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - espace-elite-files:/var/espace-elite-files

volumes:
  espace-elite-files:
    driver: local